#!/usr/bin/python

import csv

dict_type = {
    ['']
    ['1st v.p. / director']
['2nd vice president','second vice president']
['3rd vice president']
['accountant']
['advisor to the board']
['alt director', 'alt. dir to ian fair','alternate director', 'alternate director of']
['anderson']
['appointor of']
['as. sec. / as. treas.']
['assistant controller','asst. controller']
['assistant director']
['assistant secretary','assistant secretary of','asst. secretary']
['assistant treasurer','asst. treasurer']
['asst treas / director','dir / asst treasurer']
['attorney at law']
['attorney in fact']
['auditor of']
['auth. representative of']
['authorised person / signatory of','authorized', 'authorized signatory','authorized signatory of']
['bank signatory of']
['banker']
['beneficial owner of']
['beneficiary of']
['beneficiary, shareholder and director of']
['board representative of']
['bruno a. roberts']
['businessman', 'businesswoman']
['c.e.o. / secretary']
['c.f.o.','chief fin. officer','chief financial off','director / c.f.o.']
['chairman','chairman & president','chairman / board / c.e.o','chairman / director','chairman / pres / dir','chairman / president','chairman of','c.e.o','c.e.o. / pres. / dir.','chief exec. officer','chief executive off','company / director','director / c.o.o.','president - director of','president and director of','president director','president / c.e.o / director','president / diector','pres. / ch.exec. / dir.','pres. / chairman','president','president / c.e.o','president of']
['chartered accountant']
['class a director']
['class b director']
['clementi limited']
['co-trustee of trust of']
['co.','company']
['company executive']
['company secretary']
['connected of']
['controller']
['corp. director','corporate director']
['corporate secretary']
['corporation']
['correspondent addr. of']
['cramlington']
['custodian of']
['dep.chairman / tr. dir']
['dipl. ing.']
['dir / asst secretary','director / ass. sec.','director / assist sec','director / asst. sec','director, assistant secretary']
['dir / pres / sec / tre','dir / pres / treas / sec','pres / dir. / sec. / tres.']
['dir / pres / secretary','director / pres / secretary','director / pres. / secr.','director, secretary, president','pres / sec / director','pres. / dir. / sec.','president / dir / secret']
['dir / pres / treas','director - p / t','director / pres / treas','presid / treas / dir']
['dir / pres / vp / trea / sec']
['dir / vice president / cof','director / v.p.','director, vice president','vice president / director','v-president / director','vice president / c.f.o.','deputy ch. / c.e.o','vp / c.e.o.']
['dir / vice president / treas','dir. v. pres. / tre','director - vp / t','v.p. / treas. / director','vp / treasurer / directo']
['dir. / chrm. / vp / a.s.','dir. / v. p. / a.s.']
['dir. / sec. / treasure','direc / secr. / treas.','director / treas / sec','director / treasurer / s']
['dir. / vp / sec','director - v / s','director / v.pres. / sec','director / vp / secretar','director,secretary, vice president','vice president / sec. / dir.']
['dir. and sec.','director / sec','director / secretary','director, secretary','director/secretary']
['director','director (rami makhlouf) of','director of','diretor']
['director / beneficial owner of']
['director / c.e.o','director / c.e.o / pres.','director / chief investment officer','director / cob']
['director / manager','director / mgn. dir.']
['director / officer']
['director / pres / 01']
['director / president','director, president','director/president','pres / ch.invest.of / di']
['director / shareholder / beneficial owner of']
['director / shareholder of','director and shareholder of']
['director / treasurer','director/treasurer','treas. / director']
['director/officer president']
['dr. norbert marxer']
['entity similar to']
['ex vice president','exec. vice president']
['executive']
['executive director']
['executive officer']
['financial controller']
['first beneficiary of']
['first director']
['first vice president']
['foundation council']
['general accountant of']
['general counsel']
['general manager']
['gfs']
['grantee of a mortgage of']
['ibc']
['ind. non-exec. dir.']
['independent director']
['intermediary of']
['investment advisor','investment advisor of']
['joint settlor of']
['legal advisor of']
['manager-corporate']
['managing director','mng. director / china']
['member']
['member / shareholder of']
['member of foundation council of']
['mr /']
['nominated person of']
['nominee beneficial owner of']
['nominee beneficiary of']
['nominee director of']
['nominee investment advisor of']
['nominee name of']
['nominee protector of']
['nominee secretary of']
['nominee shareholder of']
['nominee trust settlor of']
['non','non executive direct']
['officer','officer of']
['ordinary director']
['owner of']
['owner, director and shareholder of']
['partner of']
['permanent director']
['personal directorship of']
['power of attorney / shareholder of']
['power of attorney of']
['pres / v.p.']
['pres. / secretary','president / secretary']
['president / treas.','president / treasurer']
['principal beneficiary of']
['probably same officer as']
['protector of']
['records & registers of']
['register of director of']
['register of shareholder of']
['registered address']
['registered agent']
['registered office']
['related entity']
['reserve director of']
['resident director of']
['resigned']
['safekeeping of']
['same address as']
['same company as']
['same intermediary as']
['same name and registration date as']
['same name as']
['sec / treas','secretary / treasurer']
['secretary','secretary of','sec']
['shareholder','shareholder (through julex foundation) of','shareholder of']
['signatory of']
['similar name and address as']
['sol director/president/secretary/treasurer','sole director/president/secretary/treasurer']
['sole director']
['sole director / sec.']
['sole shareholder of']
['sole signatory / beneficial owner of']
['sole signatory of']
['special director']
['stockbroker of']
['subscriber']
['successor protector of']
['t.c.']
['tax advisor of']
['to gary lane']
['treasurer','treasurer of']
['treasurer / asst. sec.']
['trust settlor of']
['trustee of trust of']
['tur limited']
['unit trust register of'] : 'unit trust',
['v.p / / senior trader'] : 'vice president / senior trader',
['vice president','vice president and','vice president of'] : 'vice president',
['vice president / g.m.'] : 'vice president / general manager',
['vice president / gen coun /'] : 'vice president / general counsel',
['vice president / sec.','vice president / secretary','vice president/secretary'] : 'vice president / secretary',
['vice president / sec. / trea','vice president / treas / sec'] : 'vice president / treasurer / secretary',
['vice president / treasurer','vp / treasurer'] : 'vice president / treasurer',
['vice president-finance'] : 'vice president-finance',
['vice-chairman'] : 'vice-chairman',
['vp / treas. asst sec'] : 'vice president/treasurer / assistant secretary',
    }
